version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
